Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import folium
m = folium.Map(
    location=[37.801, -122.273],
    zoom_start=10,
    tiles='Stamen Terrain'
)

folium.Marker(
    location=[37.8014, -122.273],
    popup='Mt. Hood Meadows',
    icon=folium.Icon(icon='cloud')
).add_to(m)

folium.Marker(
    location=[37.8023, -122.273],
    popup='Timberline Lodge',
    icon=folium.Icon(color='green')
).add_to(m)

folium.Marker(
    location=[37.8016, -122.2734],
    popup='Some Other Location',
    icon=folium.Icon(color='red', icon='info-sign')
).add_to(m)

m
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mfolium[39;00m
[1;32m      2[0m m [38;5;241m=[39m folium[38;5;241m.[39mMap(
[1;32m      3[0m     location[38;5;241m=[39m[[38;5;241m37.801[39m, [38;5;241m-[39m[38;5;241m122.273[39m],
[1;32m      4[0m     zoom_start[38;5;241m=[39m[38;5;241m10[39m,
[1;32m      5[0m     tiles[38;5;241m=[39m[38;5;124m'[39m[38;5;124mStamen Terrain[39m[38;5;124m'[39m
[1;32m      6[0m )
[1;32m      8[0m folium[38;5;241m.[39mMarker(
[1;32m      9[0m     location[38;5;241m=[39m[[38;5;241m37.8014[39m, [38;5;241m-[39m[38;5;241m122.273[39m],
[1;32m     10[0m     popup[38;5;241m=[39m[38;5;124m'[39m[38;5;124mMt. Hood Meadows[39m[38;5;124m'[39m,
[1;32m     11[0m     icon[38;5;241m=[39mfolium[38;5;241m.[39mIcon(icon[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcloud[39m[38;5;124m'[39m)
[1;32m     12[0m )[38;5;241m.[39madd_to(m)

[0;31mModuleNotFoundError[0m: No module named 'folium'
ModuleNotFoundError: No module named 'folium'

